version: "3.8"
services:
  basic-react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/nginx # logs directory need to be created!!
    restart: always

volumes:
  logs: #Named volume
