name: Build and send Docker Image to Dockerhub then update the host image

on:
  push:
    branches:
      - main  # Adjust the branch to your needs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/basic-react-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: SSH into the virtual machine
      - name: Deploy to virtual machine
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USER }}
          password: ${{ secrets.HOST_PASSWORD }}  
          port: 13060
          script: |
            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/basic-react-app:latest
            
            # Stop and remove the old container
            docker stop basic-react-app || true
            docker rm basic-react-app || true
            
            # Start a new container with the updated image
            docker run -d --name basic-react-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/basic-react-app:latest

